### GET All Pokemon
GET http://localhost:3000/api/pokemon/

### GET specific pokemon via id
GET http://localhost:3000/api/pokemon/1

### POST something
POST http://localhost:3000/api/pokemon/
Content-Type: application/json

{
    "pokeValue": 733,
    "name": "Toucannon",
    "type": "Cannon",
    "discovered": false
}

### PUT altered info into an existing pokemon
PUT http://localhost:3000/api/pokemon/4
Content-Type: application/json

{
    "pokeValue": 200,
    "name": "Porygon",
    "type": "Polygonal",
    "discovered": true,
    "id": 4
}

### DELETE a pokemon based on parameter ID
DELETE http://localhost:3000/api/pokemon/3

### POST add demo data
POST http://localhost:3000/api/pokemon/demo