### GET All Pokemon
GET http://localhost:3000/api/pokemon/

### GET specific pokemon via id
GET http://localhost:3000/api/pokemon/107

### POST something
POST http://localhost:3000/api/pokemon/
Content-Type: application/json

{
    "id": 1112,
    "name": "name",
    "type": "type",
    "discovered": false
}

### PUT altered info into an existing pokemon
PUT http://localhost:3000/api/pokemon/137
Content-Type: application/json

{
    "id": 137,
    "name": "Porygon",
    "type": "Polygonal",
    "discovered": true
}

### DELETE a pokemon based on parameter ID
DELETE http://localhost:3000/api/pokemon/1112

### POST add demo data
POST http://localhost:3000/api/pokemon/demo